In [2]:
import numpy as np

In [ ]:
data1 = [3.5, 5, 2.5] #list
arr1 = np.array(data1) #array1

In [ ]:
data1

[3.5, 5, 2.5]

In [ ]:
data2 = (4.5, 5, 9) #tuple
arr2 = np.array(data2)

In [ ]:
arr2

array([4.5, 5. , 9. ])

In [ ]:
arr1.ndim # array1 ning o'lchami

1

In [ ]:
arr2.ndim # array2 ning o'lchami

1

In [ ]:
data3 = [[1, 5.7, 9.8], [5, 8 ,9]] # list ichidagi list (nested list)
arr3 = np.array(data3)

In [ ]:
arr3.ndim # array3 ning o'lchami

2

In [ ]:
data4 = [[[4, 5, 8], [2, 5.5, 3]], [[8, 6, 7], [4, 5, 8]]]
arr4= np.array(data4)

In [ ]:
arr4.ndim # 3 o'lshemli massiv

3

In [ ]:
arr3

array([[1. , 5.7, 9.8],
       [5. , 8. , 9. ]])

In [ ]:
arr3.shape # qator va ustunlar sonini ko'rsatadi (q, u)

(2, 3)

In [ ]:
arr4

array([[[4. , 5. , 8. ],
        [2. , 5.5, 3. ]],

       [[8. , 6. , 7. ],
        [4. , 5. , 8. ]]])

In [ ]:
arr4.shape

(2, 2, 3)

In [ ]:
arr3

array([[1. , 5.7, 9.8],
       [5. , 8. , 9. ]])

In [ ]:
arr3.size # array3 ning elementlar soni

6

In [ ]:
arr5 = np.zeros(shape = (2, 4)) # barcha elementlari 0 ga teng bolgan (2, 4) massiv
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((2, 4)) # barcha elmentlari 1 ga teng bolgan (2, 4) massiv
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr7 = np.arange(2, 20, 2)
arr7

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr8 = np.arange(30)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr9 = np.random.rand(2, 4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) taxminiy qiymatlardan tashkil topgan
arr9

array([[0.17455288, 0.24730061, 0.56884778, 0.65433371],
       [0.43769362, 0.39346305, 0.795362  , 0.55146369]])

In [ ]:
arr10 = np.random.randint(5, size=(2,4)) # (2, 4) o'lchamli va max qiymati 5 gacha bo'lgan int sonlar
arr10

array([[1, 0, 2, 4],
       [0, 4, 3, 4]])

In [7]:
arr11 = np.random.randn(4) # (2, 4) o'lchamli --> elementlari (Normal dist)
arr11

array([ 0.37526499,  1.01935093,  0.42814416, -1.10505212])

In [8]:
arr11.ndim

1

In [13]:
arr12 = np.random.randint(4)
arr12

2

In [15]:
n = 4
arr13 = np.array(4)
arr13

array(4)