In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 5 , 8, 6]) # bir o'lchamli massivning oddiy turi
arr1

array([1, 5, 8, 6])

In [3]:
arr1.ndim

1

In [4]:
arr1 = np.array(arr1, dtype = np.float64) # massivning tipini belgilash
arr1

array([1., 5., 8., 6.])

In [5]:
arr2 = np.array([4 , 5, 7], dtype = np.int32)
arr2

array([4, 5, 7], dtype=int32)

In [6]:
arr1.dtype # massivning tipini aniqlash

dtype('float64')

In [7]:
arr2.dtype

dtype('int32')

In [8]:
arr3 = np.array([1, 8 , 3, 5]) #numpy da bu massiv o'z o'zi tip tanlaydi yaniy int64 ni
arr3

array([1, 8, 3, 5])

In [9]:
arr3.dtype

dtype('int64')

In [13]:
float_arr = arr3.astype(np.float64) # bu yerda int64 tipindagi massivni float64 tipiga o'girdik
float_arr

array([1., 8., 3., 5.])

In [14]:
data = np.array([4.0, 5, 7, 2.5])
data

array([4. , 5. , 7. , 2.5])

In [15]:
data.dtype

dtype('float64')

In [16]:
int_arr = data.astype(np.int32) # float64 tipidagi massivni int32 turiga o'zgartirdik
int_arr

array([4, 5, 7, 2], dtype=int32)