In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[-5]

50

In [ ]:
sliced_arr = arr[3:5]
sliced_arr
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [ ]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1

array([40, 50])

In [ ]:
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#2d o'lshamli massiv

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[1, 1]

5

In [ ]:
arr2d[2, 2]

9

In [20]:
sl_arr2d = arr2d[2, 1:]
sl_arr2d

array([8, 9])

In [21]:
sl_arr2d = arr2d[2, :]
sl_arr2d

array([7, 8, 9])

In [22]:
sl_arr2d = arr2d[:, :2]
sl_arr2d

array([[1, 2],
       [4, 5],
       [7, 8]])

In [27]:
# 3-o'lchamli massivlarda indeks va kesib olish asoslari

In [28]:
arr3d = np.array([[[0, 1, 2],
                   [3, 4, 5],
                   [6, 7 ,8]],

                   [[9, 10, 11],
                    [12, 13, 14],
                    [15, 16 , 17]],

                   [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
arr3d[0][1, 1]

4

In [30]:
arr3d[1][2, 1:]

array([16, 17])

In [31]:
arr3d[2][0, :2]

array([18, 19])