<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_10takrorlanmas_va_boshqa_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])
numbers = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])


In [4]:
names

array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'],
      dtype='<U10')

In [5]:
numbers

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [6]:
np.unique(names)

array(['Abdurahmon', 'Hasan', 'Sarvar', 'Temur'], dtype='<U10')

In [7]:
set(names)

{'Abdurahmon', 'Hasan', 'Sarvar', 'Temur'}

In [8]:
names

array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'],
      dtype='<U10')

In [9]:
np.unique(numbers)

array([1, 2, 3, 4])

In [10]:
arr1 = np.array([6, 0, 0, 3, 2, 5, 6])
arr2 = np.array([0, 2, 3])

In [11]:
np.in1d(arr1, arr2)

array([False,  True,  True,  True,  True, False, False])

In [12]:
names1 = np.array(['Jasur', 'Abdurahmon', 'Hasan',  'Muhammad', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])

In [13]:
np.setdiff1d(names1, names2)

array(['Jasur', 'Muhammad'], dtype='<U10')