<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_11_Fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save("data.npy", arr)

In [10]:
arr2 = np.load('data.npy')

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.savez('massivlar', a = arr, b = arr1)

In [17]:
massivlar = np.load('massivlar.npz')

In [19]:
massivlar['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
massivlar['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.savez_compressed('massiv_comp.npz', a = arr, b = arr1)


In [23]:
massiv_comp = np.load('massiv_comp.npz')

In [24]:
massiv_comp['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
massiv_comp['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])