<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_12_chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
x.ndim

2

In [8]:
y = np.array([[4,4, 4], [2, 2, 2]])
y

array([[4, 4, 4],
       [2, 2, 2]])

In [9]:
y.ndim

2

In [10]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])

In [12]:
x-y

array([[-3, -2, -1],
       [ 2,  3,  4]])

In [14]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [15]:
y / 2

array([[2., 2., 2.],
       [1., 1., 1.]])

In [16]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
y.reshape(3, 2)

array([[4, 4],
       [4, 2],
       [2, 2]])

In [25]:
y.shape = (3,2)

In [26]:
y

array([[4, 4],
       [4, 2],
       [2, 2]])

In [27]:
x.dot(y)

array([[18, 14],
       [48, 38]])

In [28]:
np.dot(x, y)

array([[18, 14],
       [48, 38]])

In [29]:
y.dot(x)

array([[20, 28, 36],
       [12, 18, 24],
       [10, 14, 18]])

In [30]:
np.dot(y, x)

array([[20, 28, 36],
       [12, 18, 24],
       [10, 14, 18]])