<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_4boolean_indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
data = np.random.randn(7, 4)
data

array([[ 0.12194904,  0.97486309,  1.05364348, -0.88595434],
       [-1.38534694, -0.51530714,  0.14284457,  0.19179314],
       [-0.43527724,  0.30184811, -1.64425482,  0.17216168],
       [-1.63886384,  0.69013315,  0.57289597, -1.07862725],
       [ 0.00818903,  0.1306919 ,  1.8499444 ,  1.08680961],
       [-0.28880973,  0.25855571, -0.29687497, -0.3645353 ],
       [ 0.36467195,  0.13818657, -1.57613735, -0.12333191]])

In [5]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [6]:
data[names == 'Hasan']

array([[ 0.12194904,  0.97486309,  1.05364348, -0.88595434],
       [ 0.00818903,  0.1306919 ,  1.8499444 ,  1.08680961]])

In [7]:
data[names == 'Elyor']

array([[-1.63886384,  0.69013315,  0.57289597, -1.07862725],
       [ 0.36467195,  0.13818657, -1.57613735, -0.12333191]])

In [13]:
data[names == 'hasan', 2:]

array([], shape=(0, 2), dtype=float64)

In [14]:
data

array([[ 0.12194904,  0.97486309,  1.05364348, -0.88595434],
       [-1.38534694, -0.51530714,  0.14284457,  0.19179314],
       [-0.43527724,  0.30184811, -1.64425482,  0.17216168],
       [-1.63886384,  0.69013315,  0.57289597, -1.07862725],
       [ 0.00818903,  0.1306919 ,  1.8499444 ,  1.08680961],
       [-0.28880973,  0.25855571, -0.29687497, -0.3645353 ],
       [ 0.36467195,  0.13818657, -1.57613735, -0.12333191]])

In [15]:
data[names == 'Hasan', :2]

array([[0.12194904, 0.97486309],
       [0.00818903, 0.1306919 ]])

In [16]:
data[names != 'Hasan']

array([[-1.38534694, -0.51530714,  0.14284457,  0.19179314],
       [-0.43527724,  0.30184811, -1.64425482,  0.17216168],
       [-1.63886384,  0.69013315,  0.57289597, -1.07862725],
       [-0.28880973,  0.25855571, -0.29687497, -0.3645353 ],
       [ 0.36467195,  0.13818657, -1.57613735, -0.12333191]])

In [31]:
data[~(names == 'Elyor')]

array([ True,  True, False,  True, False])

In [28]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[ True  True False False  True False False]


In [29]:
mask = (names == 'Hasan') | (names == 'Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [30]:
data[mask]

array([ True,  True,  True])

In [32]:
data = np.random.randn(7, 4)
data

array([[ 2.35845109,  0.15347028, -1.13353157, -0.84478102],
       [ 1.06783749, -2.34022049, -0.96204818,  1.57893014],
       [-0.09444822,  1.69527418,  0.91238399, -0.38587154],
       [-0.42541788, -0.35751374, -1.64844633, -0.3350685 ],
       [-0.33803335,  0.36671356, -0.11766371, -0.62872513],
       [-1.57657585, -0.12567629, -0.35991629, -0.13336568],
       [-0.66511359, -0.53660061,  0.39557506, -0.57261067]])

In [33]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 2.35845109  0.15347028 -1.13353157 -0.84478102]
 [ 1.06783749 -2.34022049 -0.96204818  1.57893014]
 [-0.09444822  1.69527418  0.91238399 -0.38587154]
 [-0.42541788 -0.35751374 -1.64844633 -0.3350685 ]
 [-0.33803335  0.36671356 -0.11766371 -0.62872513]
 [-1.57657585 -0.12567629 -0.35991629 -0.13336568]
 [-0.66511359 -0.53660061  0.39557506 -0.57261067]]


In [34]:
mask = (names == 'Hasan') | (names == 'Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [36]:
data[mask]

array([[ 2.35845109,  0.15347028, -1.13353157, -0.84478102],
       [ 1.06783749, -2.34022049, -0.96204818,  1.57893014],
       [-0.33803335,  0.36671356, -0.11766371, -0.62872513]])

In [37]:
data

array([[ 2.35845109,  0.15347028, -1.13353157, -0.84478102],
       [ 1.06783749, -2.34022049, -0.96204818,  1.57893014],
       [-0.09444822,  1.69527418,  0.91238399, -0.38587154],
       [-0.42541788, -0.35751374, -1.64844633, -0.3350685 ],
       [-0.33803335,  0.36671356, -0.11766371, -0.62872513],
       [-1.57657585, -0.12567629, -0.35991629, -0.13336568],
       [-0.66511359, -0.53660061,  0.39557506, -0.57261067]])

In [38]:
data[data > 0]

array([2.35845109, 0.15347028, 1.06783749, 1.57893014, 1.69527418,
       0.91238399, 0.36671356, 0.39557506])

In [39]:
data[data < 0]

array([-1.13353157, -0.84478102, -2.34022049, -0.96204818, -0.09444822,
       -0.38587154, -0.42541788, -0.35751374, -1.64844633, -0.3350685 ,
       -0.33803335, -0.11766371, -0.62872513, -1.57657585, -0.12567629,
       -0.35991629, -0.13336568, -0.66511359, -0.53660061, -0.57261067])

In [40]:
data[data < 0] = 0
data

array([[2.35845109, 0.15347028, 0.        , 0.        ],
       [1.06783749, 0.        , 0.        , 1.57893014],
       [0.        , 1.69527418, 0.91238399, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.36671356, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.39557506, 0.        ]])

In [42]:
data[data==0] = 1

In [43]:
data

array([[2.35845109, 0.15347028, 1.        , 1.        ],
       [1.06783749, 1.        , 1.        , 1.57893014],
       [1.        , 1.69527418, 0.91238399, 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 0.36671356, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 0.39557506, 1.        ]])

In [46]:
data[data != 1] = 2

In [47]:
data

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])