<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_5array_o%CA%BBqlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.swapaxes(0, 1)

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.shape = (2, 3)

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
A.swapaxes(1, 0)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
A.shape = 3,2

In [ ]:
A


array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.dot(A, A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])