<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_6mantiqiy_shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [10]:
cond = np.array([True, False, True, True, False])

In [11]:
result = np.where(cond, xarr, yarr)

In [12]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [30]:
arr = np.random.rand(4, 4)
arr

array([[0.77148435, 0.67166096, 0.31550205, 0.88378348],
       [0.98956063, 0.3449694 , 0.07116503, 0.03714897],
       [0.14846528, 0.4353995 , 0.73857235, 0.25305595],
       [0.46057412, 0.48024687, 0.98952286, 0.05473627]])

In [41]:
results = np.where(arr < 0, -2, 2)
results

array([[-2, -2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [50]:
arr[0:2] = -1

In [51]:
results = np.where(arr < 0, -2, 2)
results

array([[-2, -2, -2, -2],
       [-2, -2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])