<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_8matematik_va_statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr = np.random.randn(5, 4)
arr

array([[-0.32967936, -0.73342996,  2.40054995, -0.11792842],
       [-0.8863494 ,  0.26557769,  1.90894812, -0.20727605],
       [-0.60920941, -0.25521671,  0.47725005, -0.21289832],
       [-1.81699793, -1.30773629, -0.18801139,  0.99977981],
       [ 0.96781167, -1.46527661,  0.08735716,  0.09262555]])

In [6]:
arr.sum()

-0.9301098537359909

In [7]:
np.sum(arr)

-0.9301098537359909

In [8]:
arr.sum(axis = 1)

array([ 1.21951222,  1.08090036, -0.60007439, -2.31296581, -0.31748223])

In [9]:
arr.sum(axis = 0)

array([-2.67442443, -3.49608188,  4.68609388,  0.55430257])

In [14]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [15]:
mean = sum(data)/len(data)

In [16]:
mean

2.0

In [18]:
np.mean(data)

2.0

In [19]:
data.mean

<function ndarray.mean>

In [20]:
data.mean()

2.0

In [25]:
arr

array([[-0.32967936, -0.73342996,  2.40054995, -0.11792842],
       [-0.8863494 ,  0.26557769,  1.90894812, -0.20727605],
       [-0.60920941, -0.25521671,  0.47725005, -0.21289832],
       [-1.81699793, -1.30773629, -0.18801139,  0.99977981],
       [ 0.96781167, -1.46527661,  0.08735716,  0.09262555]])

In [26]:
arr.mean()

-0.04650549268679954

In [27]:
np.mean(arr, axis = 1)

array([ 0.30487805,  0.27022509, -0.1500186 , -0.57824145, -0.07937056])

In [28]:
arr.mean(axis=0)

array([-0.53488489, -0.69921638,  0.93721878,  0.11086051])

In [29]:
arr2 = np.random.randn(5)

In [30]:
arr2

array([-1.45122723, -1.21878301,  2.24419404, -0.47754114,  1.18605631])

In [31]:
mean = sum(arr2)/len(arr2)

In [32]:
mean

0.056539794562246205

In [33]:
len(arr2)

5

In [34]:
data

array([0, 1, 2, 3, 4])

In [36]:
data.cumsum()

array([ 0,  1,  3,  6, 10])