<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/_9tartiblash_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(4)

In [3]:
arr

array([0.60066181, 0.95406091, 0.08608215, 0.95401444])

In [5]:
sorted_arr = np.sort(arr)
sorted_arr

array([0.08608215, 0.60066181, 0.95401444, 0.95406091])

In [6]:
arr.sort()

In [7]:
arr

array([0.08608215, 0.60066181, 0.95401444, 0.95406091])

In [8]:
rev_arr = -np.sort(-arr)
rev_arr

array([0.95406091, 0.95401444, 0.60066181, 0.08608215])

In [9]:
arr

array([0.08608215, 0.60066181, 0.95401444, 0.95406091])

In [14]:
arr.sort()

In [15]:
arr2d = np.random.randn(2, 4)
arr2d

array([[ 0.65455557, -1.58900037,  1.1880181 , -0.93118983],
       [-2.3141193 ,  0.00994494, -0.37473791,  0.62235388]])

In [19]:
ustun_arr = np.sort(arr2d, axis = 1)
ustun_arr_arr

array([[-1.58900037, -0.93118983,  0.65455557,  1.1880181 ],
       [-2.3141193 , -0.37473791,  0.00994494,  0.62235388]])

In [21]:
qatar_arr = np.sort(arr2d, axis=0)
qatar_arr

array([[-2.3141193 , -0.93118983,  0.00994494,  0.62235388],
       [-1.58900037, -0.37473791,  0.65455557,  1.1880181 ]])