<a href="https://colab.research.google.com/github/Almattony/Data-science_numpy/blob/main/bo%CA%BBlim_bo%CA%BByicha_amaliy_vazifa_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr_zero_9x9 = np.zeros((9, 9))
arr_zero_9x9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr = np.arange(0, 5)
arr.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
zero_arr = np.zeros(12)
zero_arr[5] = 1
zero_arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
np.arange(20, 59)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
-np.sort(-np.arange(10))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr_3x3 = np.arange(12, 21).reshape(3, 3)
arr_3x3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr_nonzero = np.array([3, 7, 0, 0, 9, 0])
#np.nonzero(arr_nonzero)
np.where(arr_nonzero != 0)



(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr_2x2x2 = np.random.random(8).reshape(2, 2, 2)
arr_2x2x2

array([[[0.20942114, 0.56608756],
        [0.63373934, 0.3492323 ]],

       [[0.13634655, 0.60788479],
        [0.19403925, 0.72557219]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr_9x9 = np.arange(81).reshape(9, 9)
print(np.min(arr_9x9), np.max(arr_9x9))

0 80


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


In [ ]:
# shu qolda kod yozilsa faqat eng pastki qismi javob qaytaradi:
False
# agar hammasi alohida tursa javoblari quydagicha:
#1 NaN
#2 False
#3 False
#4 NaN
#5 True
#6 False


False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr_6x3 = np.ones((6, 3))
arr_3x4 = np.ones((3, 4))
arr_6x3.dot(arr_3x4) # bunda arr_6x3 ga arr_3x4 ko'paytmasi

# y ning x ga ko'paytmasi esa: y.dot(x) boladi

# yoki np.dot(x, y) qilsakda boladi



array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # 1chi sum([0, 1, 2, 3, 4] + (-1)) = 9 bunda pythondagi sum ishlayapti
from numpy import *
print(sum(range(5),-1)) # 2chi sum([0, 1, 2, 3, 4]) = 10  bu barcha numpy kutibxonasi ishlayapti, -1 esa axis rolini bajaryapti yaniy asl holati degani

# 9 va 10 chiqadi



9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])
a > b


array([False, False])

In [ ]:
a >= b

array([False, False])

In [ ]:
a < b

array([ True,  True])

In [ ]:
a <= b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
#1 NaN qiymatini qaytaradi
#2 Bu amal ZeroDivisionError yoki runtime xatosi keltirib chiqaradi sababi matematikada 0/0 bo'lish manosiz, shu xatolik bilan dastur 0 chiqardi
#3 Bu amal birnchi NaN qiymatidan Int qiymatiga ogiriladi taxminan shunday bo'ladi: -9223372036854775808 yoki 0 keyin uni dastur onlikka o'zgartiradi va shunday natiyja hosil boladi: array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr1 = np.array([20, 16, 8, 4])
arr2 = np.array([4, 8, 10, 12])
np.intersect1d(arr1, arr2, assume_unique=False, return_indices=False)

array([4, 8])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
rand_arr = np.random.uniform(-10, 10, size = 10)
print("Tasodifiy sonlar:", rand_arr)

#1 usul yaniy "%" qoldiqli bo'lish
butun_qismi = rand_arr[rand_arr > 0] % 1
butun_qismi = rand_arr[rand_arr > 0] - butun_qismi
print(butun_qismi)



#2 usul floor bu funksiya o'ziga teng yoki o'zidan eng kichik bolgan integer qiymattni qaytaradi
n = 0
floor_arr = np.zeros_like(rand_arr)
for i in range(len(rand_arr)):
  if rand_arr[i] > 0:
    floor_arr[n] = np.floor(rand_arr[i])
    n+=1
print(floor_arr[:n])



#3 usul astype bu bilan float tipidan int ga o'giramiz yaniy sonning butun qismini olamiz
javob = []
for el in rand_arr:
  if el >= 0:
    javob.append(el.astype(int))
print(javob)



#4 usul esa trunc funksiyasi sonning faqat butun qismini oladi, qoldiqni tashlab yuboradi.
trunc_arr = np.trunc(rand_arr[rand_arr > 0])
print(trunc_arr)



Tasodifiy sonlar: [-4.18316609  7.4563236   0.1176617   7.4779218   9.77944472  8.98872776
  1.29411958 -6.89778306 -5.2244001   7.69466842]
[7. 0. 7. 9. 8. 1. 7.]
[7. 0. 7. 9. 8. 1. 7.]
[7, 0, 7, 9, 8, 1, 7]
[7. 0. 7. 9. 8. 1. 7.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr_3 = np.arange(27).reshape(3,3,3)
print("Asl holi: \n", arr_3)
tol = np.arange(0, 3)
arr_3[0][:3, 0] = tol
arr_3[1][:3, 0] = tol
arr_3[2][:3, 0] = tol
print("Natiyja quydagicha: \n", arr_3)


Asl holi: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Natiyja quydagicha: 
 [[[ 0  1  2]
  [ 1  4  5]
  [ 2  7  8]]

 [[ 0 10 11]
  [ 1 13 14]
  [ 2 16 17]]

 [[ 0 19 20]
  [ 1 22 23]
  [ 2 25 26]]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [14]:
arr4  = np.random.randint(10, size = 10)
print("Asl holi:", arr4)
sorted_arr = np.sort(arr4)
print("Sortlangan turi:", sorted_arr)


Asl holi: [5 0 4 1 6 2 2 4 7 6]
Sortlangan turi: [0 1 2 2 4 4 5 6 6 7]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [26]:
arr_a = np.random.randn(5)
arr_b = np.random.randn(5)

np.allclose(arr_a, arr_b), np.array_equal(arr_a, arr_b)


(False, False)

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [7]:
array_6x3 = np.ones(shape=(6,3))
array_3x4 = np.ones(shape=(3,4))
array_6x3.dot(array_3x4)

#kopaytma = np.dot(array_3x4, array_6x3)

# Agar 3x4 o'lchamdagi matritsa2 ni 6x3 o'lchamdagi matritsa1 ga ko'paytirmoqchi bo'lsak,
# matritsa ko'paytirish qoidalariga ko'ra, bu operatsiya bajarilmaydi,
# chunki matritsa ko'paytirish uchun birinchi matritsaning ustunlari soni ikkinchi matritsaning qatorlari soniga teng bo'lishi kerak


array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [26]:
random_arr = np.random.randint(10, size=5)
max_arr = np.max(random_arr)
print(max_arr)
random_arr[] = 0
random_arr, max_arr

7


(array([3, 0, 3, 7, 4]), 7)

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`